#!/bin/sh

##   _____      _             _       _   _______       _ _ _       _     _
##  / ____|    | |           (_)     | | |__   __|     (_) (_)     | |   | |
## | |     ___ | | ___  _ __  _  __ _| |    | |_      ___| |_  __ _| |__ | |_
## | |    / _ \| |/ _ \| '_ \| |/ _` | |    | \ \ /\ / / | | |/ _` | '_ \| __|
## | |___| (_) | | (_) | | | | | (_| | |    | |\ V  V /| | | | (_| | | | | |_
##  \_____\___/|_|\___/|_| |_|_|\__,_|_|    |_| \_/\_/ |_|_|_|\__, |_| |_|\__|
##                                                             __/ |
##                                                            |___/
## This script is used to run the scala implementation of the
## solo AI for Colonial Twilight

## Set the current working directory to the directory where this script is running.
## This is important so that all of our relative path references work correctly.
cd `dirname $0`

CLASSPATH=lib/coltwi_2.11-2.2.jar:lib/scala-library-2.11.11.jar:\
lib/scala-parser-combinators_2.11-1.1.2.jar

java -cp "$CLASSPATH"  coltwi.ColonialTwilight "$@"
